version: '3.3'
services:
  nuclio:
      ports:
          - '8070:8070'
      volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
          - '/tmp:/tmp'
      container_name: nuclio-dashboard
      image: 'quay.io/nuclio/dashboard:stable-amd64'

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - "8081:8081"