version: '3.3'
services:
  nuclio:
      ports:
          - '8070:8070'
      volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
          - '/tmp:/tmp'
      container_name: nuclio-dashboard
      image: 'quay.io/nuclio/dashboard:stable-amd64'

  seeder:
    build:
      context: ./src/api
      dockerfile: Dockerfile.seeder
    image: zula-seeder
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      - mongo

  webapp:
    build:
      context: ./src/webapp
      args:
        - REACT_APP_API_URL=http://localhost:1323/api/v1
    image: zula-webapp
    ports:
      - "8080:80"
    depends_on:
      - api

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - "8081:8081"