version: '3.3'
services:
    nuclio:
        ports:
            - '8070:8070'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/tmp:/tmp'
        container_name: nuclio-dashboard
        image: 'quay.io/nuclio/dashboard:stable-amd64'